
package com.abdi.frame;

import com.abdi.swing.ScrollBar;
import com.abdi.component.item_list;
import com.abdi.event.EventMenu;
import com.abdi.event.PublicEvent;
import com.abdi.model.Model_User_Account;
import java.util.ArrayList;
import java.util.List;
import net.miginfocom.swing.MigLayout;

public class menu extends javax.swing.JPanel {

   private List<Model_User_Account> userAccount;
    public menu() {
        initComponents();
        init();
    }

    public void init(){
        sp.setVerticalScrollBar(new ScrollBar());
        menu_list.setLayout(new MigLayout("fillx", "0[]0", "0[]0"));
        userAccount = new ArrayList<>();
        PublicEvent.getInstance().addEventMenu(new EventMenu() {
            @Override
            public void newUser(List<Model_User_Account> users) {
                for (Model_User_Account d: users){
                    userAccount.add(d);
                     menu_list.add(new item_list(d.getUserName()), "wrap");
                     menu_list.repaint();
                     menu_list.revalidate();
                }
            }
        });
        show_Message();
    }
    
    private void show_Message(){
        menu_list.removeAll();
        for(Model_User_Account d : userAccount){
             menu_list.add(new item_list(d.getUserName()), "wrap");
        }
        menu_list.repaint();
        menu_list.revalidate();
    }
    
    private void show_Group(){
        menu_list.removeAll();
        for(int i = 0; i < 3; i++){
            menu_list.add(new item_list("group "+ i), "wrap");
        }
        menu_list.repaint();
        menu_list.revalidate();
    }
    
    private void show_Podcast(){
        menu_list.removeAll();
        for(int i = 0; i < 5; i++){
            menu_list.add(new item_list("podcast "+ i), "wrap");
        }
        menu_list.repaint();
        menu_list.revalidate();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu = new javax.swing.JLayeredPane();
        menu_message = new com.abdi.component.menu_button();
        menu_group = new com.abdi.component.menu_button();
        menu_podcast = new com.abdi.component.menu_button();
        sp = new javax.swing.JScrollPane();
        menu_list = new javax.swing.JLayeredPane();

        setBackground(new java.awt.Color(242, 242, 242));

        menu.setBackground(new java.awt.Color(222, 219, 219));
        menu.setOpaque(true);
        menu.setLayout(new java.awt.GridLayout(1, 3));

        menu_message.setIconSelected(new javax.swing.ImageIcon(getClass().getResource("/com/abdi/icon/chat_color.png"))); // NOI18N
        menu_message.setIconSimple(new javax.swing.ImageIcon(getClass().getResource("/com/abdi/icon/chat_no_color.png"))); // NOI18N
        menu_message.setSelected(true);
        menu_message.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_messageActionPerformed(evt);
            }
        });
        menu.add(menu_message);

        menu_group.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/abdi/icon/group_chat_no_color.png"))); // NOI18N
        menu_group.setIconSelected(new javax.swing.ImageIcon(getClass().getResource("/com/abdi/icon/group_chat_color.png"))); // NOI18N
        menu_group.setIconSimple(new javax.swing.ImageIcon(getClass().getResource("/com/abdi/icon/group_chat_no_color.png"))); // NOI18N
        menu_group.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_groupActionPerformed(evt);
            }
        });
        menu.add(menu_group);

        menu_podcast.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/abdi/icon/podcast_no_color.png"))); // NOI18N
        menu_podcast.setIconSelected(new javax.swing.ImageIcon(getClass().getResource("/com/abdi/icon/podcast_color.png"))); // NOI18N
        menu_podcast.setIconSimple(new javax.swing.ImageIcon(getClass().getResource("/com/abdi/icon/podcast_no_color.png"))); // NOI18N
        menu_podcast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_podcastActionPerformed(evt);
            }
        });
        menu.add(menu_podcast);

        sp.setBackground(new java.awt.Color(242, 242, 242));
        sp.setBorder(null);
        sp.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        menu_list.setBackground(new java.awt.Color(242, 242, 242));
        menu_list.setOpaque(true);

        javax.swing.GroupLayout menu_listLayout = new javax.swing.GroupLayout(menu_list);
        menu_list.setLayout(menu_listLayout);
        menu_listLayout.setHorizontalGroup(
            menu_listLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        menu_listLayout.setVerticalGroup(
            menu_listLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 425, Short.MAX_VALUE)
        );

        sp.setViewportView(menu_list);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
            .addComponent(sp)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sp))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void menu_messageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_messageActionPerformed
        if(!menu_message.isSelected()){
            menu_message.setSelected(true);
            menu_group.setSelected(false);
            menu_podcast.setSelected(false);
            show_Message();
        }
    }//GEN-LAST:event_menu_messageActionPerformed

    private void menu_groupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_groupActionPerformed
       if(!menu_group.isSelected()){
            menu_message.setSelected(false);
            menu_group.setSelected(true);
            menu_podcast.setSelected(false);
            show_Group();
        }
    }//GEN-LAST:event_menu_groupActionPerformed

    private void menu_podcastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_podcastActionPerformed
        if(!menu_podcast.isSelected()){
            menu_message.setSelected(false);
            menu_group.setSelected(false);
            menu_podcast.setSelected(true);
            show_Podcast();
        }
    }//GEN-LAST:event_menu_podcastActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane menu;
    private com.abdi.component.menu_button menu_group;
    private javax.swing.JLayeredPane menu_list;
    private com.abdi.component.menu_button menu_message;
    private com.abdi.component.menu_button menu_podcast;
    private javax.swing.JScrollPane sp;
    // End of variables declaration//GEN-END:variables
}
